/**
 * Deterministic post-processor for cover letter content.
 * Scans generated paragraphs and fixes LLM writing violations.
 */

export interface PostProcessorResult {
  paragraphs: string[]
  fixes: string[]
}

// ---- Blocklists ----

const AI_CLICHES = [
  'i am excited to',
  'i was thrilled to',
  'i am thrilled to',
  'i am passionate about',
  'i am eager to',
  'uniquely positioned',
  'perfect fit',
  'hit the ground running',
  'synergy',
  'leverage my expertise',
  'leverage my skills',
  'bring to the table',
  'think outside the box',
  'go above and beyond',
  'dynamic environment',
  'fast-paced environment',
  'results-driven',
  'detail-oriented individual',
  'hard-working individual',
  'team player',
  'proven track record',
  'take my career to the next level',
  'align perfectly',
  'aligns perfectly',
]

const FLOWERY_ADJECTIVES = [
  'innovative',
  'revolutionary',
  'game-changing',
  'groundbreaking',
  'cutting-edge',
  'world-class',
  'best-in-class',
  'state-of-the-art',
  'transformative',
  'unparalleled',
  'unprecedented',
  'remarkable',
  'extraordinary',
  'exceptional',
]

const PASSIVE_CLOSINGS = [
  'hope to hear',
  'hoping to hear',
  'look forward to hearing',
  'looking forward to hearing',
  'would love to hear',
  'would love the opportunity to discuss',
  'please do not hesitate',
  "don't hesitate",
  'please feel free',
  'at your earliest convenience',
]

const AI_META_LANGUAGE = [
  'as an ai',
  'as a language model',
  'generated by',
  'this cover letter was',
  'this letter was generated',
  'ai-generated',
  'ai generated',
]

// ---- Sentence Helpers ----

function splitSentences(text: string): string[] {
  // Split on sentence-ending punctuation followed by a space or end of string
  return text
    .split(/(?<=[.!?])\s+/)
    .map(s => s.trim())
    .filter(s => s.length > 0)
}

function joinSentences(sentences: string[]): string {
  return sentences.join(' ')
}

function startsWithI(sentence: string): boolean {
  return /^I\s/.test(sentence.trim())
}

// ---- Rule Processors ----

function fixEmDashes(text: string, fixes: string[]): string {
  const original = text
  const fixed = text.replace(/[\u2014\u2013]/g, ' - ').replace(/ {2,}/g, ' ')
  if (fixed !== original) {
    fixes.push('Replaced em/en dashes with hyphens')
  }
  return fixed
}

function fixBrackets(text: string, fixes: string[]): string {
  const original = text
  // Replace bracketed placeholders with contextual fallback
  const fixed = text
    .replace(/\[Hiring Manager\]/gi, 'Hiring Manager')
    .replace(/\[Company(?: Name)?\]/gi, 'your team')
    .replace(/\[Your Name\]/gi, '')
    .replace(/\[.*?\]/g, '') // Remove any remaining brackets
    .replace(/ {2,}/g, ' ')
    .trim()
  if (fixed !== original) {
    fixes.push('Removed bracketed placeholders')
  }
  return fixed
}

function fixAiCliches(text: string, fixes: string[]): string {
  const lower = text.toLowerCase()
  for (const cliche of AI_CLICHES) {
    if (lower.includes(cliche)) {
      fixes.push(`Removed AI cliche: "${cliche}"`)
    }
  }

  // Remove sentences containing cliches rather than trying to rephrase
  const sentences = splitSentences(text)
  const filtered = sentences.filter(sentence => {
    const sentLower = sentence.toLowerCase()
    return !AI_CLICHES.some(cliche => sentLower.includes(cliche))
  })

  // If we'd remove all sentences, keep the original
  if (filtered.length === 0) return text
  return joinSentences(filtered)
}

function fixFloweryAdjectives(text: string, fixes: string[]): string {
  let result = text
  for (const adj of FLOWERY_ADJECTIVES) {
    const pattern = new RegExp(`\\b${adj}\\b`, 'gi')
    if (pattern.test(result)) {
      fixes.push(`Removed flowery adjective: "${adj}"`)
      result = result.replace(pattern, '').replace(/ {2,}/g, ' ').trim()
    }
  }
  return result
}

function fixConsecutiveIStarts(text: string, fixes: string[]): string {
  const sentences = splitSentences(text)
  if (sentences.length < 2) return text

  let fixed = false
  for (let i = 1; i < sentences.length; i++) {
    if (startsWithI(sentences[i]) && startsWithI(sentences[i - 1])) {
      // Restructure by removing leading "I" and using alternative phrasing
      const s = sentences[i]
      // Try to restructure: "I built X" -> "This included building X"
      const match = s.match(
        /^I\s+(\w+ed|built|led|designed|created|developed|implemented)\s+(.*)$/i
      )
      if (match) {
        sentences[i] =
          `This included ${match[1].toLowerCase().replace(/ed$/, 'ing').replace(/built/, 'building').replace(/led/, 'leading')} ${match[2]}`
        fixed = true
      } else {
        // Generic restructure: "I have X" -> "My background includes X"
        const genericMatch = s.match(/^I\s+(have|had|am|was)\s+(.*)$/i)
        if (genericMatch) {
          sentences[i] = `My background includes ${genericMatch[2]}`
          fixed = true
        }
      }
    }
  }

  if (fixed) {
    fixes.push('Restructured consecutive "I" sentence starts')
  }
  return joinSentences(sentences)
}

function fixPassiveClosings(text: string, fixes: string[]): string {
  const lower = text.toLowerCase()
  for (const closing of PASSIVE_CLOSINGS) {
    if (lower.includes(closing)) {
      // Replace the sentence containing the passive closing
      const sentences = splitSentences(text)
      const filtered = sentences.filter(s => {
        const sLower = s.toLowerCase()
        return !PASSIVE_CLOSINGS.some(c => sLower.includes(c))
      })

      // Add a call-to-value closing
      filtered.push(
        'I would welcome the chance to discuss how my experience can contribute to your team.'
      )

      fixes.push('Replaced passive closing with call-to-value')
      return joinSentences(filtered)
    }
  }
  return text
}

function fixAiMetaLanguage(text: string, fixes: string[]): string {
  const sentences = splitSentences(text)
  const filtered = sentences.filter(sentence => {
    const sentLower = sentence.toLowerCase()
    const hasMetaLanguage = AI_META_LANGUAGE.some(phrase => sentLower.includes(phrase))
    if (hasMetaLanguage) {
      fixes.push('Removed AI meta-language')
    }
    return !hasMetaLanguage
  })

  if (filtered.length === 0) return text
  return joinSentences(filtered)
}

// ---- Main Post-Processor ----

/**
 * Process an array of cover letter paragraphs through all writing rules.
 * Returns cleaned paragraphs and a list of fixes applied.
 */
export function postProcessCoverLetter(paragraphs: string[]): PostProcessorResult {
  const fixes: string[] = []

  const processed = paragraphs.map(paragraph => {
    let text = paragraph

    // Apply rules in order of priority
    text = fixEmDashes(text, fixes)
    text = fixBrackets(text, fixes)
    text = fixAiMetaLanguage(text, fixes)
    text = fixAiCliches(text, fixes)
    text = fixFloweryAdjectives(text, fixes)
    text = fixConsecutiveIStarts(text, fixes)
    text = fixPassiveClosings(text, fixes)

    // Final cleanup: normalize whitespace
    text = text.replace(/ {2,}/g, ' ').trim()

    return text
  })

  // Deduplicate fixes
  const uniqueFixes = [...new Set(fixes)]

  return { paragraphs: processed, fixes: uniqueFixes }
}
